"""
Axion AI — Concrete process profiles
=====================================

Two profiles ship out of the box:

  - **pilot**: CSTR + binary distillation column (the original product).
  - **batch_reactor**: Exothermic batch reactor with cooling jacket.

Either can be made active via `AXION_PROCESS_PROFILE=<name>` or by
POSTing to `/api/profile/select`.
"""

from __future__ import annotations

from .process_profile import ProcessProfile, TagSpec, register


# ─────────────────────────────────────────────────────────────────────────────
# Pilot — CSTR + distillation column
# Captures everything that was hardcoded in api/report.py, api/uploads.py,
# and the soft-sensor / LSTM training scripts.
# ─────────────────────────────────────────────────────────────────────────────

PILOT_PROFILE = ProcessProfile(
    name="pilot",
    display_name="CSTR + Distillation Column",
    description="Exothermic CSTR feeding a binary distillation column (pilot).",
    tags=[
        # Reactor
        TagSpec("cstr.T_R_C",       "Reactor Temperature",  "°C",     None,  82.0),
        TagSpec("cstr.T_J_C",       "Jacket Temperature",   "°C"),
        TagSpec("cstr.C_A",         "Reactant Conc. A",     "mol/m³"),
        TagSpec("cstr.F_feed",      "Feed Flow",            "m³/h"),
        TagSpec("cstr.F_cool",      "Coolant Flow",         "m³/h"),
        TagSpec("cstr.T_feed_C",    "Feed Temperature",     "°C",  is_kpi=False),
        TagSpec("cstr.T_cool_in_C", "Coolant Inlet Temp",   "°C",  is_kpi=False),
        TagSpec("cstr.P_R",         "Reactor Pressure",     "bar", is_kpi=False),
        TagSpec("cstr.conversion",  "Conversion",           "",       0.70, None),
        # Column
        TagSpec("column.x_D",       "Distillate Comp.",     "",    is_kpi=False),
        TagSpec("column.x_B_A",     "Bottom Comp. A",       "",    is_kpi=False),
        TagSpec("column.purity_B",  "Product Purity",       "%",      98.5, None),
        TagSpec("column.T_top_C",   "Column Top Temp.",     "°C"),
        TagSpec("column.T_bot_C",   "Column Bottom Temp.",  "°C"),
        TagSpec("column.RR",        "Reflux Ratio",         ""),
        TagSpec("column.F_vap_kgh", "Vapor Flow",           "kg/h", is_kpi=False),
        TagSpec("column.Q_reb_kW",  "Reboiler Duty",        "kW",     None,  320.0),
        TagSpec("column.P_top_bar", "Top Pressure",         "bar", is_kpi=False),
        TagSpec("column.P_bot_bar", "Bottom Pressure",      "bar", is_kpi=False),
    ],
    feature_cols=[
        "column.T_bot_C", "column.T_top_C", "column.RR",
        "column.Q_reb_kW", "column.F_vap_kgh", "column.P_top_bar", "cstr.C_A",
    ],
    target_col="column.purity_B",
    scenarios=[
        "normal", "thermal_drift", "feed_perturbation",
        "reactor_instability", "quality_degradation",
        "energy_waste", "product_grade_change",
        "sensor_failure", "product_grade_transition",
    ],
    purity_kpi="column.purity_B",
    purity_spec_min=98.5,
    measured_tags=[
        "cstr.T_R_C", "cstr.T_J_C", "cstr.C_A", "cstr.conversion",
        "cstr.P_R", "cstr.T_feed_C", "cstr.T_cool_in_C",
        "column.purity_B", "column.x_D", "column.x_B_A",
        "column.T_top_C", "column.T_bot_C",
        "column.F_vap_kgh", "column.Q_reb_kW",
        "column.P_top_bar", "column.P_bot_bar",
    ],
    operational_limits={
        "cstr.T_R_C":      {"low": 76.0, "high": 82.0, "rate_per_min": 0.4},
        "column.purity_B": {"low": 98.5, "high": None, "rate_per_min": 0.5},
        "column.Q_reb_kW": {"low": None, "high": 320.0, "rate_per_min": 5.0},
    },
    rule_pack_path="recommendations.rules_pilot:PILOT_RULES",
)


# ─────────────────────────────────────────────────────────────────────────────
# Batch reactor — exothermic, with cooling jacket
# Tags: 8 process variables that mirror what a real batch reactor exposes.
# Scenarios are generated by `scripts/generate_batch_scenarios.py`.
# ─────────────────────────────────────────────────────────────────────────────

BATCH_PROFILE = ProcessProfile(
    name="batch_reactor",
    display_name="Exothermic Batch Reactor",
    description=(
        "Single-vessel exothermic batch reactor with cooling jacket. "
        "Demonstrates the platform on a process other than the pilot."
    ),
    tags=[
        TagSpec("batch.T_R_C",      "Reactor Temperature",    "°C",   None,  95.0),
        TagSpec("batch.T_J_C",      "Jacket Temperature",     "°C"),
        TagSpec("batch.T_cool_in_C", "Coolant Inlet Temp",    "°C",   is_kpi=False),
        TagSpec("batch.C_A",        "Reactant A Concentration", "mol/m³"),
        TagSpec("batch.C_P",        "Product Concentration",   "mol/m³"),
        TagSpec("batch.conversion", "Batch Conversion",       "",      0.85, None),
        TagSpec("batch.F_cool",     "Coolant Flow",           "m³/h"),
        TagSpec("batch.dHdt",       "Heat Release Rate",      "kW",    None, 250.0),
    ],
    feature_cols=[
        "batch.T_R_C", "batch.T_J_C", "batch.T_cool_in_C",
        "batch.C_A", "batch.F_cool",
    ],
    target_col="batch.C_P",
    scenarios=[
        "batch_normal", "batch_runaway", "batch_slow_kinetics",
    ],
    purity_kpi="batch.conversion",
    purity_spec_min=0.85,
    measured_tags=[
        "batch.T_R_C", "batch.T_J_C", "batch.T_cool_in_C",
        "batch.C_A", "batch.C_P", "batch.conversion",
        "batch.dHdt",
    ],
    operational_limits={
        "batch.T_R_C":      {"low": 20.0, "high": 95.0, "rate_per_min": 1.5},
        "batch.dHdt":       {"low": None, "high": 250.0, "rate_per_min": 25.0},
        "batch.conversion": {"low": 0.85, "high": None, "rate_per_min": None},
    },
    rule_pack_path="recommendations.rules_batch:BATCH_RULES",
)


# Register both
register(PILOT_PROFILE)
register(BATCH_PROFILE)
